### ISSUE TITLE
【環境整備】example追加

### ISSUE THREAD

**Issue by Shimpei-GANGAN** [Shimpei-GANGAN/eslint-config-next-typescript#5]
### 内容
- Next.js + TypeScript環境における設定例を追加したい

### NOTE
- 本リポジトリが重くなるので何度もcreate-next-appしなくて良い。ESLint、Prettierの設定方法が分かればいい。
- custom-create-next-appについては別リポジトリで作成する

### TODO
- [ ] Next.js + TypeScript用example追加
- [ ] Next.js + TypeScript + Storybook用example追加
- [ ] Next.js + TypeScript + Storybook + MUI用example追加
